# Generated by Django 3.0.5 on 2020-06-21 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_user_info_follo_wers'),
    ]

    operations = [
        migrations.CreateModel(
            name='followuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='follo_wers',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='following_count',
        ),
        migrations.DeleteModel(
            name='follow',
        ),
    ]
