# Generated by Django 3.0.5 on 2020-06-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200621_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='year',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
