# Generated by Django 3.0.5 on 2020-06-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200628_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='username',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
