# Generated by Django 3.0.5 on 2020-07-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_followuser_follow_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuser',
            name='follow_check',
        ),
    ]
