# Generated by Django 3.0.6 on 2020-05-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0002_doubts_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts_data',
            name='doubt_file',
            field=models.FileField(upload_to='static/doubt_files'),
        ),
    ]
