# Generated by Django 3.0.6 on 2020-05-31 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0003_auto_20200530_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubts_data',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doubts_data',
            name='doubt_language',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doubts_data',
            name='doubt_file',
            field=models.FileField(blank=True, upload_to='static/doubt_files'),
        ),
    ]
