# Generated by Django 3.0.5 on 2020-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0004_auto_20200531_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubts_data',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
