# Generated by Django 3.0.5 on 2020-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0006_doubts_data_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubts_data',
            name='doubt_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
