# Generated by Django 3.0.5 on 2020-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0008_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts_data',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
