# Generated by Django 3.0.5 on 2020-06-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0005_doubts_data_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubts_data',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
