# Generated by Django 3.0.5 on 2020-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0009_auto_20200608_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
