# Generated by Django 3.0.5 on 2020-06-09 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doubt', '0010_auto_20200608_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts_data',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
